=== aferrandiz1/bridje-framework/bridje-data/hmodel.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" targetNamespace="http://www.bridje.org/schemas/hmodel" xmlns:tns="http://www.bridje.org/schemas/hmodel" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="hmodel" type="tns:hModel"/>

    <xs:complexType name="hModel">
        <xs:annotation>
            <xs:documentation>
                Hierarchical model definition.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hEntityData">
                <xs:sequence>
                    <xs:element name="license" type="tns:string" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>
                                License text to be used for this model.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="entitys" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>
                                List of model entitys
                            </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="entity" type="tns:hEntity" minOccurs="0" maxOccurs="unbounded">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Represents an entity of the hierarchical model.
                                        </xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="enums" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>
                                List of model enumerators
                            </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="enum" type="tns:hEnum" minOccurs="0" maxOccurs="unbounded">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Represents an enumerator of the model, to be use as a source for the enumerators fields of the entitys.
                                        </xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="packageName" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Package name for java clases.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="namespace" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Target namespace for the xml schema.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hEntityData">
        <xs:annotation>
            <xs:documentation>
                Data common to all entity like classes.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="description" type="tns:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        The description of this entity.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        A list of fields for this entity.
                    </xs:documentation>
                </xs:annotation>
                <xs:element name="string" type="tns:hStringField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a string field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="list" type="tns:hListField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a field that holds a collection of objects.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="enum" type="tns:hEnumField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a field that holds an enumerator value.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="boolean" type="tns:hBooleanField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a boolean field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="element" type="tns:hElementField">
                    <xs:annotation>
                        <xs:documentation>
                            A field that holds a reference to another entity of the model.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name for this object, This value will be used to identify the entity withing the model, it will be the class and xml type name also.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="extendsFrom" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    Entity that this object will extends from.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="customizable" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this entity is customizable or not. If true a base class will be generated for this entity.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hStringField">
        <xs:annotation>
            <xs:documentation>
                Represents a string field.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hBasicField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="defaultValue" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            The default value for this field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hBooleanField">
        <xs:annotation>
            <xs:documentation>
                Represents a boolean field.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hBasicField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="defaultValue" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation>
                            The default value for this field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hListField">
        <xs:annotation>
            <xs:documentation>
                Represents a field that holds a collection of objects.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hField">
                <xs:sequence>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="element" type="tns:hListElement">
                            <xs:annotation>
                                <xs:documentation>
                                    An element of a list field.
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:choice>
                </xs:sequence>
                <xs:attribute name="of" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="wrapper" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation>
                            
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hEnumField">
        <xs:annotation>
            <xs:documentation>
                Represents a field that holds an enumerator value.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hBasicField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            The name of the enumerator for this field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hBasicField">
        <xs:annotation>
            <xs:documentation>
                Root class for all the basic fields objects.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="access" type="xs:enum">
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hField">
        <xs:annotation>
            <xs:documentation>
                Root class for all the fields objects.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The field name
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="description" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The fiel description
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="required" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this field is required.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="readonly" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this field is read only.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="isTransient" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this field transient.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hListElement">
        <xs:annotation>
            <xs:documentation>
                An element of a list field.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The entity or class this element maps to.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the element.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="description" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    If this field is required.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hElementField">
        <xs:annotation>
            <xs:documentation>
                A field that holds a reference to another entity of the model.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            The name of the entity that this field refers to.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hParentField">
        <xs:annotation>
            <xs:documentation>
                Defines the parent of an entity.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the parent field to be use.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="type" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the entity or class the parent object must extends or implement.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hEntity">
        <xs:annotation>
            <xs:documentation>
                Represents an entity of the hierarchical model.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hEntityData">
                <xs:sequence>
                    <xs:element name="parent" type="tns:hParentField" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>
                                The parent field of this entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hEnum">
        <xs:annotation>
            <xs:documentation>
                Represents an enumerator of the model, to be use as a source for the enumerators fields of the entitys.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="description" type="tns:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        The description of the enumerator.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        A list of values for this enumerator.
                    </xs:documentation>
                </xs:annotation>
                <xs:element name="value" type="tns:hEnumValue">
                    <xs:annotation>
                        <xs:documentation>
                            An enumerator value, this class defines the constans of the object representing by the HEnum object.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the enumerator, this value will identify the enumerator withing the model.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hEnumValue">
        <xs:annotation>
            <xs:documentation>
                An enumerator value, this class defines the constans of the object representing by the HEnum object.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the value.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="description" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The description of the value.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="hFieldAccess">
        <xs:annotation>
            <xs:documentation>
                Defines the type of access a field may have.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="ATTRIBUTE">
                <xs:annotation>
                    <xs:documentation>
                        The field will be mapped from an xml attribute.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ELEMENT">
                <xs:annotation>
                    <xs:documentation>
                        The field will be mapped from an xml element.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== aferrandiz1/bridje-framework/bridje-data/src/main/resources/BRIDJE-INF/models/hmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<hmodel 
    xmlns="http://www.bridje.org/schemas/hmodel" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.bridje.org/schemas/hmodel file:/E:/Projects/bridje-framework/bridje-data/hmodel.xsd"
    name="HModel" packageName="org.bridje.data.hmodel" extendsFrom="HEntityData" 
    namespace="http://www.bridje.org/schemas/hmodel"
    customizable="true">

    <license>
Copyright 2015 Bridje Framework.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
    </license>
    <string name="packageName" access="ATTRIBUTE" description="Package name for java clases." />
    <string name="namespace" access="ATTRIBUTE" description="Target namespace for the xml schema." />
    <string name="license" access="ELEMENT" description="License text to be used for this model." />
    <list name="entitys" of="HEntity" wrapper="true" description="List of model entitys" >
        <element name="entity" type="HEntity" />
    </list>
    <list name="enums" of="HEnum" wrapper="true" description="List of model enumerators" >
        <element name="enum" type="HEnum" />
    </list>
    <description>Hierarchical model definition.</description>

    <entitys>
        <entity name="HEntityData" customizable="true" >
            <description>Data common to all entity like classes.</description>
            <string name="name" access="ATTRIBUTE" description="The name for this object, This value will be used to identify the entity withing the model, it will be the class and xml type name also." />
            <string name="extendsFrom" access="ATTRIBUTE" description="Entity that this object will extends from." />
            <string name="description" access="ELEMENT" description="The description of this entity." />
            <boolean name="customizable" access="ATTRIBUTE" defaultValue="false" description="If this entity is customizable or not. If true a base class will be generated for this entity." />
            <list name="fields" of="HField" description="A list of fields for this entity.">
                <element name="string" type="HStringField" />
                <element name="list" type="HListField" />
                <element name="enum" type="HEnumField" />
                <element name="boolean" type="HBooleanField" />
                <element name="element" type="HElementField" />
            </list>
        </entity>
        <entity name="HStringField" extendsFrom="HBasicField" customizable="true">
            <description>Represents a string field.</description>
            <string name="defaultValue" access="ATTRIBUTE" description="The default value for this field." />
        </entity>
        <entity name="HBooleanField" extendsFrom="HBasicField" customizable="true">
            <description>Represents a boolean field.</description>
            <boolean name="defaultValue" access="ATTRIBUTE" description="The default value for this field." />
        </entity>
        <entity name="HListField" extendsFrom="HField" customizable="true">
            <description>Represents a field that holds a collection of objects.</description>
            <parent name="entity" type="HEntityData" />
            <string name="of" access="ATTRIBUTE" description="The type of the list represented by this field." />
            <boolean name="wrapper" access="ATTRIBUTE" defaultValue="false" description="If this fields needs to be wrapped." />
            <list name="elements" of="HListElement" description="Elements " >
                <element name="element" type="HListElement" />
            </list>
        </entity>
        <entity name="HEnumField" extendsFrom="HBasicField" customizable="true">
            <description>Represents a field that holds an enumerator value.</description>
            <string name="type" access="ATTRIBUTE" description="The name of the enumerator for this field." />
        </entity>
        <entity name="HBasicField" extendsFrom="HField" customizable="true">
            <description>Root class for all the basic fields objects.</description>
            <enum name="access" type="HFieldAccess" access="ATTRIBUTE" description="" />
        </entity>
        <entity name="HField" customizable="true" >
            <description>Root class for all the fields objects.</description>
            <string name="name" access="ATTRIBUTE" description="The field name" />
            <string name="description" access="ATTRIBUTE" description="The fiel description" />
            <boolean name="required" access="ATTRIBUTE" required="true" defaultValue="false" description="If this field is required." />
            <boolean name="readonly" access="ATTRIBUTE" required="true" defaultValue="false" description="If this field is read only." />
            <boolean name="isTransient" access="ATTRIBUTE" required="true" defaultValue="false" description="If this field transient." />
        </entity>
        <entity name="HListElement" customizable="true">
            <description>An element of a list field.</description>
            <parent name="listField" type="HListField" />
            <string name="type" access="ATTRIBUTE" description="The entity or class this element maps to." />
            <string name="name" access="ATTRIBUTE" description="The name of the element." />
            <string name="description" access="ATTRIBUTE" description="If this field is required." />
        </entity>
        <entity name="HElementField" extendsFrom="HField" customizable="true">
            <description>A field that holds a reference to another entity of the model.</description>
            <string name="type" access="ATTRIBUTE" description="The name of the entity that this field refers to." />
        </entity>
        <entity name="HParentField" >
            <description>Defines the parent of an entity.</description>
            <string name="name" access="ATTRIBUTE" description="The name of the parent field to be use." />
            <string name="type" access="ATTRIBUTE" description="The name of the entity or class the parent object must extends or implement." />
        </entity>
        <entity name="HEntity" extendsFrom="HEntityData">
            <description>Represents an entity of the hierarchical model.</description>
            <parent name="model" type="HModel" />
            <element name="parent" type="HParentField" description="The parent field of this entity." />
        </entity>
        <entity name="HEnum" >
            <description>Represents an enumerator of the model, to be use as a source for the enumerators fields of the entitys.</description>
            <parent name="model" type="HModel" />
            <string name="name" access="ATTRIBUTE" description="The name of the enumerator, this value will identify the enumerator withing the model." />
            <string name="description" access="ELEMENT" description="The description of the enumerator." />
            <list name="values" of="HEnumValue" description="A list of values for this enumerator." >
                <element name="value" type="HEnumValue" />
            </list>
        </entity>
        <entity name="HEnumValue" >
            <description>An enumerator value, this class defines the constans of the object representing by the HEnum object.</description>
            <string name="name" access="ATTRIBUTE" description="The name of the value." />
            <string name="description" access="ATTRIBUTE" description="The description of the value." />
        </entity>
    </entitys>
    <enums>
        <enum name="HFieldAccess">
            <description>Defines the type of access a field may have.</description>
            <value name="ATTRIBUTE" description="The field will be mapped from an xml attribute." />
            <value name="ELEMENT" description="The field will be mapped from an xml element." />
        </enum>
    </enums>
</hmodel>
