=== aferrandiz1/bridje-framework/bridje-data/hmodel.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" targetNamespace="http://www.bridje.org/schemas/hmodel" xmlns:tns="http://www.bridje.org/schemas/hmodel" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="hmodel" type="tns:hModel"/>

    <xs:complexType name="hModel">
        <xs:annotation>
            <xs:documentation>
                Hierarchical model definition.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hEntityData">
                <xs:sequence>
                    <xs:element name="license" type="tns:string" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>
                                License text to be used for this model.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="entitys" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>
                                List of model entitys
                            </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="entity" type="tns:hEntity" minOccurs="0" maxOccurs="unbounded">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Represents an entity of the hierarchical model.
                                        </xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="enums" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>
                                List of model enumerators
                            </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="enum" type="tns:hEnum" minOccurs="0" maxOccurs="unbounded">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Represents an enumerator of the model, to be use as a source for the enumerators fields of the entitys.
                                        </xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="packageName" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Package name for java clases.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="namespace" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            Target namespace for the xml schema.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hEntityData">
        <xs:annotation>
            <xs:documentation>
                Data common to all entity like classes.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="description" type="tns:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        The description of this entity.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        A list of fields for this entity.
                    </xs:documentation>
                </xs:annotation>
                <xs:element name="string" type="tns:hStringField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a string field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="list" type="tns:hListField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a field that holds a collection of objects.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="enum" type="tns:hEnumField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a field that holds an enumerator value.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="boolean" type="tns:hBooleanField">
                    <xs:annotation>
                        <xs:documentation>
                            Represents a boolean field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="element" type="tns:hElementField">
                    <xs:annotation>
                        <xs:documentation>
                            A field that holds a reference to another entity of the model.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name for this object, This value will be used to identify the entity withing the model, it will be the class and xml type name also.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="extendsFrom" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    Entity that this object will extends from.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="customizable" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this entity is customizable or not. If true a base class will be generated for this entity.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hStringField">
        <xs:annotation>
            <xs:documentation>
                Represents a string field.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hBasicField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="defaultValue" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            The default value for this field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hBooleanField">
        <xs:annotation>
            <xs:documentation>
                Represents a boolean field.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hBasicField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="defaultValue" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation>
                            The default value for this field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hListField">
        <xs:annotation>
            <xs:documentation>
                Represents a field that holds a collection of objects.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hField">
                <xs:sequence>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="element" type="tns:hListElement">
                            <xs:annotation>
                                <xs:documentation>
                                    An element of a list field.
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:choice>
                </xs:sequence>
                <xs:attribute name="of" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="wrapper" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation>
                            
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hEnumField">
        <xs:annotation>
            <xs:documentation>
                Represents a field that holds an enumerator value.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hBasicField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            The name of the enumerator for this field.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hBasicField">
        <xs:annotation>
            <xs:documentation>
                Root class for all the basic fields objects.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="access" type="xs:enum">
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hField">
        <xs:annotation>
            <xs:documentation>
                Root class for all the fields objects.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The field name
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="description" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The fiel description
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="required" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this field is required.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="readonly" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this field is read only.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="isTransient" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>
                    If this field transient.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hListElement">
        <xs:annotation>
            <xs:documentation>
                An element of a list field.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The entity or class this element maps to.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the element.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="description" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    If this field is required.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hElementField">
        <xs:annotation>
            <xs:documentation>
                A field that holds a reference to another entity of the model.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hField">
                <xs:sequence>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>
                            The name of the entity that this field refers to.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hParentField">
        <xs:annotation>
            <xs:documentation>
                Defines the parent of an entity.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the parent field to be use.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="type" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the entity or class the parent object must extends or implement.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hEntity">
        <xs:annotation>
            <xs:documentation>
                Represents an entity of the hierarchical model.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="tns:hEntityData">
                <xs:sequence>
                    <xs:element name="parent" type="tns:hParentField" minOccurs="0" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>
                                The parent field of this entity.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="hEnum">
        <xs:annotation>
            <xs:documentation>
                Represents an enumerator of the model, to be use as a source for the enumerators fields of the entitys.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="description" type="tns:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        The description of the enumerator.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        A list of values for this enumerator.
                    </xs:documentation>
                </xs:annotation>
                <xs:element name="value" type="tns:hEnumValue">
                    <xs:annotation>
                        <xs:documentation>
                            An enumerator value, this class defines the constans of the object representing by the HEnum object.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the enumerator, this value will identify the enumerator withing the model.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="hEnumValue">
        <xs:annotation>
            <xs:documentation>
                An enumerator value, this class defines the constans of the object representing by the HEnum object.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name of the value.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="description" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The description of the value.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="hFieldAccess">
        <xs:annotation>
            <xs:documentation>
                Defines the type of access a field may have.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="ATTRIBUTE">
                <xs:annotation>
                    <xs:documentation>
                        The field will be mapped from an xml attribute.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ELEMENT">
                <xs:annotation>
                    <xs:documentation>
                        The field will be mapped from an xml element.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== aferrandiz1/bridje-framework/bridje-data/src/main/resources/BRIDJE-INF/models/rmodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<hmodel 
    xmlns="http://www.bridje.org/schemas/hmodel" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.bridje.org/schemas/hmodel file:/E:/Projects/bridje-framework/bridje-data/hmodel.xsd"
    name="RModel" packageName="org.bridje.data.rmodel" 
    namespace="http://www.bridje.org/schemas/rmodel"
    customizable="true">

    <license>
Copyright 2015 Bridje Framework.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
    </license>
    <entitys>
        <entity name="REntity">
            <list name="fields" of="RField" wrapper="false">
                <elements>
                    <element name="string" type="RStringField" />
                </elements>
            </list>
        </entity>
        <entity name="RField">
            <string name="name" access="ATTIBUTE" />
        </entity>
        <entity name="RStringField" extendsFrom="RField">
            <boolean name="trim" access="ATTIBUTE" defaultValue="false" />
        </entity>
    </entitys>
</hmodel>
